# ==========================================
# Functional settings
# ==========================================
# Change prefix key
set -g prefix C-w
unbind C-b

# Reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Status Bar Position
set-option -g status-position bottom

# Indexing and Timing
set -g base-index 1
set -sg escape-time 0

# Vim-like keybinds
set-window-option -g mode-keys vi
bind v copy-mode
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection

# ==========================================
# VISUAL SETTINGS 
# ==========================================
# 1. Prevent shell from changing the name to the path
set-option -g allow-rename off

# 2. Force Tmux to name windows after the current command (e.g. nvim, zsh, python)
set-option -g automatic-rename on
set-option -g automatic-rename-format "#{pane_current_command}"

# Catppuccin Configuration
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none" # none == default
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# Style Definitions
set -g @custom_status_separator "#[fg=#{@thm_surface_2},bg=default,none]"
set -g @custom_status_inline "󱋱"
set -g @custom_text "#[fg=#{@thm_subtext_0}]"

# Status Left
set -g status-left-length 80
set -g status-left ""

# Status Right
set -g status-right-length 160
set -g status-right ""
set -ga status-right "#{E:#{@custom_status_separator}}"
set -ga status-right "#[fg=#{@thm_blue}]#{E:#{@custom_status_inline}} 󰉋 #{E:#{@custom_text}}#{b:pane_current_path} "
set -ga status-right "#{E:#{@custom_status_separator}}"
set -ga status-right "#[fg=#{@thm_lavender}]#{E:#{@custom_status_inline}} 󱨰 #{E:#{@custom_text}}%Y-%m-%d "
set -ga status-right "#[fg=#{@thm_lavender}]#{E:#{@custom_status_inline}} 󰅐 #{E:#{@custom_text}}%H:%M "

# Pane Look and Feel
setw -g pane-border-status off
setw -g pane-border-format ""
setw -g pane-active-border-style "fg=#{@thm_peach},bg=default"
setw -g pane-border-style "fg=#{@thm_overlay_2},bg=default"
setw -g pane-border-lines single

# Command Line Look and Feel
set -g message-style "bg=#{@thm_bg}, fg=#{@thm_fg}"
set -g message-command-style "bg=#{@thm_mantle}, fg=#{@thm_fg}"

# General Status Bar Styling
set -g status-style "bg=#{@thm_mantle}"
set -g status-justify "left"

set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

# ==========================================
# PLUGINS
# ==========================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

# Resurrect Settings
set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
